export const defaultRoomServiceItems = [
    {
      item: "Towels",
      description: "Extra towels delivered to your room.",
      category: "room_service",
      department: "housekeeping",
      tags: ["towels", "extra_towels"],
      is_paid: false,
      price: null,
      currency: null,
      is_upsell: false,
      is_active: true,
      requires_quantity: true,
      requires_time: false,
      max_quantity: 5,
      request_type: "request",
      cooldown_minutes: 60
    },
    {
      item: "Bottled Water",
      description: "Still or sparkling bottled water delivered to your room.",
      category: "room_service",
      department: "housekeeping",
      tags: ["water", "bottled_water", "drinks"],
      is_paid: false,
      price: null,
      currency: null,
      is_upsell: false,
      is_active: true,
      requires_quantity: true,
      requires_time: false,
      max_quantity: 4,
      request_type: "request",
      cooldown_minutes: 30
    },
    {
      item: "Extra Pillows",
      description: "Extra pillows delivered to your room.",
      category: "room_service",
      department: "housekeeping",
      tags: ["pillows", "extra_pillows"],
      is_paid: false,
      price: null,
      currency: null,
      is_upsell: false,
      is_active: true,
      requires_quantity: true,
      max_quantity: 4,
      requires_time: false,
      request_type: "request",
      cooldown_minutes: 60
    },
    {
      item: "Wine Bottle",
      description: "A bottle of red or white wine delivered to your room.",
      category: "room_service",
      department: "kitchen",
      tags: ["wine", "bottle_of_wine", "drinks", "alcohol"],
      is_paid: true,
      price: null, 
      currency: null, 
      is_upsell: true,
      is_active: true,
      requires_quantity: false,
      requires_time: false,
      request_type: "upgrade",
      cooldown_minutes: 120
    },
    {
      item: "Toothbrush Kit",
      description: "Toothbrush and toothpaste kit delivered to your room.",
      category: "room_service",
      department: "housekeeping",
      tags: ["toothbrush", "toothpaste", "dental_kit", "amenities"],
      is_paid: false,
      price: null,
      currency: null,
      is_upsell: false,
      is_active: true,
      requires_quantity: false,
      requires_time: false,
      request_type: "request",
      cooldown_minutes: 60
    },
    {
      item: "Slippers",
      description: "Comfortable slippers for in-room use.",
      category: "room_service",
      department: "housekeeping",
      tags: ["slippers", "footwear", "comfort", "amenities"],
      is_paid: false,
      price: null,
      currency: null,
      is_upsell: false,
      is_active: true,
      requires_quantity: false,
      requires_time: false,
      request_type: "request",
      cooldown_minutes: 60
    },
    {
      item: "Extra Blankets",
      description: "Additional blankets delivered to your room.",
      category: "room_service",
      department: "housekeeping",
      tags: ["blankets", "extra_blankets", "bedding", "comfort"],
      is_paid: false,
      price: null,
      currency: null,
      is_upsell: false,
      is_active: true,
      requires_quantity: true,
      requires_time: false,
      max_quantity: 3,
      request_type: "request",
      cooldown_minutes: 60
    },
    {
      item: "Iron and Ironing Board",
      description: "Iron and ironing board delivered to your room.",
      category: "room_service",
      department: "housekeeping",
      tags: ["iron", "ironing_board", "clothes", "laundry_amenity"],
      is_paid: false,
      price: null,
      currency: null,
      is_upsell: false,
      is_active: true,
      requires_quantity: false,
      requires_time: false,
      max_quantity: null,
      request_type: "request",
      cooldown_minutes: 120
    },
    {
      item: "Hair Dryer",
      description: "Hair dryer delivered to your room.",
      category: "room_service",
      department: "housekeeping",
      tags: ["hair_dryer", "bathroom", "styling", "amenities"],
      is_paid: false,
      price: null,
      currency: null,
      is_upsell: false,
      is_active: true,
      requires_quantity: false,
      requires_time: false,
      max_quantity: null,
      request_type: "request",
      cooldown_minutes: 60
    },
    {
      item: "Bathrobe",
      description: "Comfortable bathrobe for your stay.",
      category: "room_service",
      department: "housekeeping",
      tags: ["bathrobe", "robe", "comfort", "amenities"],
      is_paid: false,
      price: null,
      currency: null,
      is_upsell: false,
      is_active: true,
      requires_quantity: true,
      requires_time: false,
      max_quantity: 2,
      request_type: "request",
      cooldown_minutes: 60
    },
    {
      item: "Coffee and Tea Service",
      description: "In-room coffee and tea making facilities with supplies.",
      category: "room_service",
      department: "kitchen",
      tags: ["coffee", "tea", "beverages", "kettle", "in_room_dining"],
      is_paid: false,
      price: null,
      currency: null,
      is_upsell: false,
      is_active: true,
      requires_quantity: false, // Request is for a refresh or initial setup
      requires_time: false,
      max_quantity: null,
      request_type: "request",
      cooldown_minutes: 30 
    },
    {
      item: "Ice Bucket",
      description: "Ice bucket with fresh ice delivered to your room.",
      category: "room_service",
      department: "kitchen",
      tags: ["ice", "ice_bucket", "drinks", "cooling"],
      is_paid: false,
      price: null,
      currency: null,
      is_upsell: false,
      is_active: true,
      requires_quantity: false,
      requires_time: false,
      max_quantity: null,
      request_type: "request",
      cooldown_minutes: 30
    },
    {
      item: "Champagne Bottle",
      description: "Premium champagne bottle delivered to your room.",
      category: "room_service",
      department: "kitchen",
      tags: ["champagne", "celebration", "drinks", "alcohol", "sparkling_wine"],
      is_paid: true,
      price: null, 
      currency: null, 
      is_upsell: true,
      is_active: true,
      requires_quantity: false,
      requires_time: false,
      max_quantity: null,
      request_type: "upgrade",
      cooldown_minutes: 120
    },
    {
      item: "Premium Snacks",
      description: "Selection of premium snacks and chocolates.",
      category: "room_service",
      department: "kitchen",
      tags: ["snacks", "chocolate", "food", "minibar_item", "treats"],
      is_paid: true,
      price: null, 
      currency: null, 
      is_upsell: true,
      is_active: true,
      requires_quantity: false, // Assumes a pre-defined selection or hotel specifies
      requires_time: false,
      max_quantity: null,
      request_type: "upgrade",
      cooldown_minutes: 60
    },
    {
      item: "Shaving Kit",
      description: "Shaving razor and cream.",
      category: "room_service",
      department: "housekeeping",
      tags: ["shaving_kit", "razor", "shaving_cream", "amenities", "toiletries"],
      is_paid: false,
      price: null,
      currency: null,
      is_upsell: false,
      is_active: true,
      requires_quantity: false,
      requires_time: false,
      request_type: "request",
      cooldown_minutes: 60
    },
    {
      item: "Feminine Hygiene Products",
      description: "Sanitary napkins or tampons available upon request.",
      category: "room_service",
      department: "housekeeping",
      tags: ["feminine_hygiene", "sanitary_products", "tampons", "pads", "amenities"],
      is_paid: false, 
      price: null,
      currency: null,
      is_upsell: false,
      is_active: true,
      requires_quantity: false, // Typically a small pack
      requires_time: false,
      request_type: "request",
      cooldown_minutes: 60
    },
    {
      item: "International Power Adapter",
      description: "Universal power adapter for various plug types.",
      category: "room_service",
      department: "front_desk",
      tags: ["power_adapter", "universal_adapter", "charger_adapter", "travel_gadget"],
      is_paid: false, // Or a small deposit, hotel dependent
      price: null,
      currency: null,
      is_upsell: false,
      is_active: true,
      requires_quantity: false,
      requires_time: false,
      request_type: "request",
      cooldown_minutes: 120 // Longer as it's usually borrowed
    }
]; 